### ISSUE TITLE
Testing a new installation?

### ISSUE THREAD

**Issue by winnall** [topeju/autopi_mqtt#4]
I've installed Autopi in my Zero SR electric motorbike and can access it from both the Autopi website and with SSH in my own LAN. I can publish messages from the Zero to the MQTT server in my LAN using `mosquitto_pub`.

I've gone through the installation steps in the `README.md`, though I don't really understand the Autopi software. I've looked at `syslog` and can't see any obvious errors relating to MQTT.

But my MQTT server is not receiving any messages from the Zero. How do I test this stuff from the command line of the Autopi or elsewhere? Do I have to get on the bike and ride it around?

Steve

**Comment by topeju** [comment]
Sorry, I didn't get a chance to respond earlier. Did you get this to work?

You mention that you can publish messages on the LAN, but can you access your MQTT broker from the internet too (do note the security concerns there)?

(Second note: I don't use this custom code myself anymore, as I switched to using the built-in MQTT -- I got this to work by using the AutoPi itself as the MQTT broker, but that is completely ok for my use case, which involves connecting to the broker from a second device in the car.)

**Comment by winnall** [comment]
No, I didn’t get it to work. But I read your comment somewhere else about using the built-in MQTT instead so I’m doing that instead. I’ve now only got to access some information for MQTT to publish…
